image: node:12.16.3

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm ci
  only:
    - master

build:
  stage: build
  script:
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master